// 后端地址
const LOCAL_SERVER = "XXX"
const DEV_SERVER = "XXX"
const DIST_SERVER = "XXX"
// 前端地址
const LOCAL_CLIENT = "XXX"
const DEV_CLIENT = "XXX"
const DIST_CLIENT = "XXX"
// 图片地址
const LOCAL_IMG = "XXX"
const DEV_IMG = "XXX"
const DIST_IMG = "XXX"
// wgt地址
const LOCAL_WGT = "XXX"
const DEV_WGT = "XXX"
const DIST_WGT = "XXX"

export const HOST = process.env.VUE_APP_DIST === "1" ? DIST_SERVER : process.env.NODE_ENV === "production" ? DEV_SERVER : LOCAL_SERVER
// 前端地址
export const CLIENT_URL = process.env.VUE_APP_DIST === "1" ? DIST_CLIENT : process.env.NODE_ENV === "production" ? DEV_CLIENT : LOCAL_CLIENT
export const IMG_HOST = process.env.VUE_APP_DIST === "1" ? DIST_IMG : process.env.NODE_ENV === "production" ? DEV_IMG : LOCAL_IMG
export const WGT_HOST = process.env.VUE_APP_DIST === "1" ? DIST_WGT : process.env.NODE_ENV === "production" ? DEV_WGT : LOCAL_WGT

export const LOGIN_URL = HOST + "/core-login-auth/no-auth/login"
export const VCODE_URL = HOST + "/core-login-auth/no-auth/vcode"
export const REGIST_URL = HOST + "/core-login-auth/no-auth/register"
export const REFRESH_URL = HOST + "/core-login-auth/refresh"
export const LOGOUT_URL = HOST + "/core-login-auth/logout"
export const SYSPROPERTY_QUERY_ALL_URL = HOST + "/sys-property/properties"
export const CREATE_MISSION_URL = HOST + "/core-mission/create"
export const MISSION_RULE_URL = HOST + "/core-mission-rule/list"
export const MISSION_LIST_URL = HOST + "/core-mission/clist"
export const MISSION_DETAIL_WITH_PUBLISHED_URL = HOST + "/core-mission/mission-detail"
export const ACCEPT_MISSION_URL = HOST + "/core-mission/accept-mission"
export const MY_ACCEPT_MISSION_LIST_URL = HOST + "/core-mission/my-mission-accept-list"
export const MY_PUBLISH_MISSION_LIST_URL = HOST + "/core-mission/my-mission-publish-list"
export const MISSION_DETAIL_URL = HOST + "/core-mission/queryById"
export const DELETE_MISSION_URL = HOST + "/core-mission/delete"
export const ADD_MISSION_COUNT_URL = HOST + "/core-mission-detail/add-count"
export const ADD_MISSION_PRICE_URL = HOST + "/core-mission-detail/add-price"
export const OFF_MISSION_URL = HOST + "/core-mission/off-mission"
export const FINISH_MISSION_URL = HOST + "/core-mission/finish-mission"
export const REVIEW_MISSION_DETAIL_URL = HOST + "/core-mission/review-mission-detail"
export const REVIEW_MISSION_URL = HOST + "/core-mission/review-mission"
export const REVIEW_MISSION_LIST_URL = HOST + "/core-mission/review-mission-list"
export const QRCODE_IMG_URL = HOST + "/core-qrcode/img"
export const COMPLAINT_URL = HOST + "/core-mission-complaint/complaint"
export const NOTICE_URL = HOST + "/social-notice/clist"
export const RECHARGE_DEPOSIT_URL = HOST + "/core-deposit-purchase/recharge"
export const IMG_LIST_URL = HOST + "/core-img/query"
export const PARTNER_QUERY_URL = HOST + "/core-partner/queryById"
export const PARTNER_DETAIL_URL = HOST + "/core-partner/partner-detail"
export const PARTNER_INFO_URL = HOST + "/core-partner/info"
export const TOP_MISSION_URL = HOST + "/core-top/top-mission"
export const CHAT_REPLAY_URL = HOST + "/social-review-chat/add-chat"
export const FOLLOW_URL = HOST + "/social-follow/follow"
export const FANS_URL = HOST + "/social-follow/follow/list"
export const ADVICE_URL = HOST + "/sys-advice/submit"
export const UPDATE_URL = HOST + "/core-version/no-auth/update-version"
export const RECHARGE_MISSION_COIN_URL = HOST + "/core-mission/recharge"
export const WITHDRAWAL_MISSION_COIN_URL = HOST + "/core-mission/withdrawal-mission-coin"
export const WITHDRAWAL_EARNING_URL = HOST + "/core-mission/withdrawal-earning"
export const WITHDRAWAL_DEPOSIT_URL = HOST + "/core-deposit-purchase/withdrawal"
export const SET_ALIPAY_ACCOUNT_URL = HOST + "/sys-user/set-alipay"
export const BUY_PARTNER_URL = HOST + "/core-partner-purchase/buy"
export const SUBORDINATE_URL = HOST + "/sys-user/subordinate"
export const SHOP_URL = HOST + "/shop/detail"
export const QUESTION_LIST_URL = HOST + "/core-question/clist"
export const HOME_DATA_URL = HOST + "/home/data"
export const CURRENCY_DETAIL_URL = HOST + "/core-currency-change/clist"
// 七牛云上传图片
export const QINIUKODO_UPLOAD_TOKEN_URL = HOST + "/qiniu/kodo/create-token"
export const MISSION_STEP_URL = HOST + "/core-mission-detail-step/list"
